# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-13 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='video_mp4',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='video_ogg',
        ),
    ]
