# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import videoapp.models
import videokit.models
import videosite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_thumbnail_cache',
            field=models.ImageField(blank=True, null=True, storage=videosite.storage_backends.CacheMediaStorage(), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_cache',
            field=videokit.models.VideoField(duration_field='video_duration', height_field='video_height', mimetype_field='video_mimetype', rotation_field='video_rotation', storage=videosite.storage_backends.CacheMediaStorage(), thumbnail_field='video_thumbnail_cache', upload_to=videoapp.models.upload_to, width_field='video_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=videosite.storage_backends.PublicMediaStorage(), upload_to=b''),
        ),
    ]
