# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_auto_20180114_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_mp4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_ogg',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
