# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
