# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171221_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='./pic_folder/None/no-img.jpg', upload_to='./pic_folder/'),
        ),
    ]
